### ISSUE TITLE
Errors Compiling with Arduino 1.8.19 and Teensyduino 1.58 

### ISSUE THREAD

**Issue by djpeterso23662** [mxmxmx/temps_utile-#56]
Good afternoon!  I am trying to run Arduino Verify on temps_utile- on a fresh install of Arduino 1.8.19 and Teensyduino 1.58 on Windows 10.  I am receiving the errors below.  I have the board, CPU Speed, and Optimize settings set for TU as instructed.  Do you have any suggestions, please, how I can proceed?  I apologize for sharing the long compiler input-- Teensy is not a platform I am familiar with.  Thanks so much! 

```
Arduino: 1.8.19 (Windows 10), TD: 1.58, Board: "Teensy 3.2 / 3.1, Serial, 120 MHz (overclock), Faster, US English"

C:\arduino-1.8.19\arduino-builder -dump-prefs -logger=machine -hardware C:\arduino-1.8.19\hardware -tools C:\arduino-1.8.19\tools-builder -tools C:\arduino-1.8.19\hardware\tools\avr -built-in-libraries C:\arduino-1.8.19\libraries -libraries C:\Users\rfuser37\Documents\Arduino\libraries -fqbn=teensy:avr:teensy31:usb=serial,speed=120,opt=o2std,keys=en-us -ide-version=10819 -build-path C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009 -warnings=none -build-cache C:\Users\rfuser37\AppData\Local\Temp\8\arduino_cache_904313 -verbose C:\msys64\home\rfuser37\temps_utile-\soft\t_u_REV\t_u_REV.ino

C:\arduino-1.8.19\arduino-builder -compile -logger=machine -hardware C:\arduino-1.8.19\hardware -tools C:\arduino-1.8.19\tools-builder -tools C:\arduino-1.8.19\hardware\tools\avr -built-in-libraries C:\arduino-1.8.19\libraries -libraries C:\Users\rfuser37\Documents\Arduino\libraries -fqbn=teensy:avr:teensy31:usb=serial,speed=120,opt=o2std,keys=en-us -ide-version=10819 -build-path C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009 -warnings=none -build-cache C:\Users\rfuser37\AppData\Local\Temp\8\arduino_cache_904313 -verbose C:\msys64\home\rfuser37\temps_utile-\soft\t_u_REV\t_u_REV.ino

Using board 'teensy31' from platform in folder: C:\arduino-1.8.19\hardware\teensy\avr

Using core 'teensy3' from platform in folder: C:\arduino-1.8.19\hardware\teensy\avr

Detecting libraries used...

"C:\\arduino-1.8.19\\hardware\\teensy/../tools/arm/bin/arm-none-eabi-g++" -E -CC -x c++ -w -g -Wall -ffunction-sections -fdata-sections -nostdlib -mno-unaligned-access -fno-exceptions -fpermissive -felide-constructors -std=gnu++14 -Wno-error=narrowing -fno-rtti -mthumb -mcpu=cortex-m4 -fsingle-precision-constant -D__MK20DX256__ -DTEENSYDUINO=158 -DARDUINO=10819 -DARDUINO_TEENSY32 -DF_CPU=120000000 -DUSB_SERIAL -DLAYOUT_US_ENGLISH "-IC:\\arduino-1.8.19\\hardware\\teensy\\avr\\cores\\teensy3" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\t_u_REV.ino.cpp" -o nul

Alternatives for EEPROM.h: [EEPROM@2.0]

ResolveLibrary(EEPROM.h)

  -> candidates: [EEPROM@2.0]

"C:\\arduino-1.8.19\\hardware\\teensy/../tools/arm/bin/arm-none-eabi-g++" -E -CC -x c++ -w -g -Wall -ffunction-sections -fdata-sections -nostdlib -mno-unaligned-access -fno-exceptions -fpermissive -felide-constructors -std=gnu++14 -Wno-error=narrowing -fno-rtti -mthumb -mcpu=cortex-m4 -fsingle-precision-constant -D__MK20DX256__ -DTEENSYDUINO=158 -DARDUINO=10819 -DARDUINO_TEENSY32 -DF_CPU=120000000 -DUSB_SERIAL -DLAYOUT_US_ENGLISH "-IC:\\arduino-1.8.19\\hardware\\teensy\\avr\\cores\\teensy3" "-IC:\\arduino-1.8.19\\hardware\\teensy\\avr\\libraries\\EEPROM" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\t_u_REV.ino.cpp" -o nul

Using cached library dependencies for file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\TU_ADC.cpp

Using cached library dependencies for file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\TU_app_menu.cpp

Using cached library dependencies for file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\TU_app_storage.cpp

Using cached library dependencies for file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\TU_apps.cpp

Using cached library dependencies for file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\TU_bitmaps.cpp

Using cached library dependencies for file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\TU_debug.cpp

Using cached library dependencies for file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\TU_digital_inputs.cpp

Using cached library dependencies for file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\TU_global_config.cpp

Using cached library dependencies for file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\TU_input_map.cpp

Using cached library dependencies for file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\TU_menus.cpp

Using cached library dependencies for file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\TU_outputs.cpp

Using cached library dependencies for file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\TU_patterns.cpp

Using cached library dependencies for file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\TU_strings.cpp

Using cached library dependencies for file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\TU_ui.cpp

Using cached library dependencies for file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\peaks_resources.cpp

Using cached library dependencies for file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\streams_lorenz_generator.cpp

Using cached library dependencies for file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\streams_resources.cpp

Using cached library dependencies for file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\src\ADC\ADC_Module.cpp

Using cached library dependencies for file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\src\ADC\OC_util_ADC.cpp

Using cached library dependencies for file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\src\ADC\RingBuffer.cpp

Using cached library dependencies for file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\src\ADC\RingBufferDMA.cpp

Using cached library dependencies for file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\src\SH1106_128x64_driver.cpp

Using cached library dependencies for file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\src\display.cpp

Using cached library dependencies for file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\src\util_misc.cpp

Using cached library dependencies for file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\src\weegfx.cpp

Using cached library dependencies for file: C:\arduino-1.8.19\hardware\teensy\avr\libraries\EEPROM\EEPROM.cpp

Generating function prototypes...

"C:\\arduino-1.8.19\\hardware\\teensy/../tools/arm/bin/arm-none-eabi-g++" -E -CC -x c++ -w -g -Wall -ffunction-sections -fdata-sections -nostdlib -mno-unaligned-access -fno-exceptions -fpermissive -felide-constructors -std=gnu++14 -Wno-error=narrowing -fno-rtti -mthumb -mcpu=cortex-m4 -fsingle-precision-constant -D__MK20DX256__ -DTEENSYDUINO=158 -DARDUINO=10819 -DARDUINO_TEENSY32 -DF_CPU=120000000 -DUSB_SERIAL -DLAYOUT_US_ENGLISH "-IC:\\arduino-1.8.19\\hardware\\teensy\\avr\\cores\\teensy3" "-IC:\\arduino-1.8.19\\hardware\\teensy\\avr\\libraries\\EEPROM" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\t_u_REV.ino.cpp" -o "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\preproc\\ctags_target_for_gcc_minus_e.cpp"

"C:\\arduino-1.8.19\\tools-builder\\ctags\\5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\preproc\\ctags_target_for_gcc_minus_e.cpp"

Compiling sketch...

"C:\\arduino-1.8.19\\hardware\\teensy/../tools/precompile_helper" "C:\\arduino-1.8.19\\hardware\\teensy\\avr/cores/teensy3" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009" "C:\\arduino-1.8.19\\hardware\\teensy/../tools/arm/bin/arm-none-eabi-g++" -x c++-header -O2 -g -Wall -ffunction-sections -fdata-sections -nostdlib -mno-unaligned-access -MMD -fno-exceptions -fpermissive -felide-constructors -std=gnu++14 -Wno-error=narrowing -fno-rtti -mthumb -mcpu=cortex-m4 -fsingle-precision-constant -D__MK20DX256__ -DTEENSYDUINO=158 -DARDUINO=10819 -DARDUINO_TEENSY32 -DF_CPU=120000000 -DUSB_SERIAL -DLAYOUT_US_ENGLISH "-IC:\\arduino-1.8.19\\hardware\\teensy\\avr/cores/teensy3" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009/pch/Arduino.h" -o "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009/pch/Arduino.h.gch"

Using previously compiled file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\pch\Arduino.h.gch

Using previously compiled file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\TU_bitmaps.cpp.o

Using previously compiled file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\TU_outputs.cpp.o

Using previously compiled file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\TU_strings.cpp.o

Using previously compiled file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\TU_global_config.cpp.o

Using previously compiled file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\TU_digital_inputs.cpp.o

Using previously compiled file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\TU_menus.cpp.o

Using previously compiled file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\TU_ADC.cpp.o

"C:\\arduino-1.8.19\\hardware\\teensy/../tools/arm/bin/arm-none-eabi-g++" -c -O2 -g -Wall -ffunction-sections -fdata-sections -nostdlib -mno-unaligned-access -MMD -fno-exceptions -fpermissive -felide-constructors -std=gnu++14 -Wno-error=narrowing -fno-rtti -mthumb -mcpu=cortex-m4 -fsingle-precision-constant -D__MK20DX256__ -DTEENSYDUINO=158 -DARDUINO=10819 -DARDUINO_TEENSY32 -DF_CPU=120000000 -DUSB_SERIAL -DLAYOUT_US_ENGLISH "-IC:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009/pch" "-IC:\\arduino-1.8.19\\hardware\\teensy\\avr\\cores\\teensy3" "-IC:\\arduino-1.8.19\\hardware\\teensy\\avr\\libraries\\EEPROM" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\t_u_REV.ino.cpp" -o "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\t_u_REV.ino.cpp.o"

Using previously compiled file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\TU_debug.cpp.o

Using previously compiled file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\streams_lorenz_generator.cpp.o

Using previously compiled file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\streams_resources.cpp.o

Using previously compiled file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\TU_app_menu.cpp.o

Using previously compiled file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\TU_apps.cpp.o

Using previously compiled file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\TU_patterns.cpp.o

Using previously compiled file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\peaks_resources.cpp.o

Using previously compiled file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\TU_input_map.cpp.o

Using previously compiled file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\TU_app_storage.cpp.o

Using previously compiled file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\TU_ui.cpp.o

In file included from C:\msys64\home\rfuser37\temps_utile-\soft\t_u_REV\APP_CLK.ino:29:

C:\msys64\home\rfuser37\temps_utile-\soft\t_u_REV\TU_pattern_edit.h: In member function 'void TU::PatternEditor<Owner>::handleButtonUp(const UI::Event&)':

TU_pattern_edit.h:407: warning: '~' on an expression of type 'bool' 

  407 |       fine_coarse_ = (~fine_coarse_) & 1u;

      |                        ^~~~~~~~~~~~

C:\msys64\home\rfuser37\temps_utile-\soft\t_u_REV\TU_pattern_edit.h:407:24: note: did you mean to use logical not ('!')?

C:\msys64\home\rfuser37\temps_utile-\soft\t_u_REV\TU_pattern_edit.h: In instantiation of 'void TU::PatternEditor<Owner>::handleButtonUp(const UI::Event&) [with Owner = Clock_channel]':

C:\msys64\home\rfuser37\temps_utile-\soft\t_u_REV\TU_pattern_edit.h:293:9:   required from 'void TU::PatternEditor<Owner>::HandleButtonEvent(const UI::Event&) [with Owner = Clock_channel]'

C:\msys64\home\rfuser37\temps_utile-\soft\t_u_REV\APP_CLK.ino:2703:50:   required from here

TU_pattern_edit.h:407: warning: '~' on an expression of type 'bool' 

C:\msys64\home\rfuser37\temps_utile-\soft\t_u_REV\TU_pattern_edit.h:407:24: note: did you mean to use logical not ('!')?

Using previously compiled file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\src\SH1106_128x64_driver.cpp.o

Using previously compiled file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\src\util_misc.cpp.o

Using previously compiled file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\src\display.cpp.o

Using previously compiled file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\src\ADC\RingBuffer.cpp.o

Using previously compiled file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\src\weegfx.cpp.o

Using previously compiled file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\src\ADC\ADC_Module.cpp.o

Using previously compiled file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\src\ADC\OC_util_ADC.cpp.o

Using previously compiled file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\sketch\src\ADC\RingBufferDMA.cpp.o

Compiling libraries...

Compiling library "EEPROM"

Using previously compiled file: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_build_868009\libraries\EEPROM\EEPROM.cpp.o

Compiling core...

Using precompiled core: C:\Users\rfuser37\AppData\Local\Temp\8\arduino_cache_904313\core\core_8383bc6b34a5e230b55ed140c641d6cf.a

Linking everything together...

"C:\\arduino-1.8.19\\hardware\\teensy/../tools/arm/bin/arm-none-eabi-gcc" -O2 -Wl,--gc-sections,--relax,--defsym=__rtc_localtime=1682255371 "-TC:\\arduino-1.8.19\\hardware\\teensy\\avr\\cores\\teensy3/mk20dx256.ld" -mthumb -mcpu=cortex-m4 -fsingle-precision-constant -o "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009/t_u_REV.ino.elf" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\TU_ADC.cpp.o" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\TU_app_menu.cpp.o" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\TU_app_storage.cpp.o" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\TU_apps.cpp.o" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\TU_bitmaps.cpp.o" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\TU_debug.cpp.o" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\TU_digital_inputs.cpp.o" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\TU_global_config.cpp.o" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\TU_input_map.cpp.o" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\TU_menus.cpp.o" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\TU_outputs.cpp.o" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\TU_patterns.cpp.o" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\TU_strings.cpp.o" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\TU_ui.cpp.o" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\peaks_resources.cpp.o" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\streams_lorenz_generator.cpp.o" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\streams_resources.cpp.o" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\t_u_REV.ino.cpp.o" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\src\\ADC\\ADC_Module.cpp.o" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\src\\ADC\\OC_util_ADC.cpp.o" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\src\\ADC\\RingBuffer.cpp.o" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\src\\ADC\\RingBufferDMA.cpp.o" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\src\\SH1106_128x64_driver.cpp.o" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\src\\display.cpp.o" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\src\\util_misc.cpp.o" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\sketch\\src\\weegfx.cpp.o" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009\\libraries\\EEPROM\\EEPROM.cpp.o" "C:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009/..\\arduino_cache_904313\\core\\core_8383bc6b34a5e230b55ed140c641d6cf.a" "-LC:\\Users\\rfuser37\\AppData\\Local\\Temp\\8\\arduino_build_868009" -larm_cortexM4l_math -lm -lstdc++

c:/arduino-1.8.19/hardware/tools/arm/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/bin/ld.exe: c:/arduino-1.8.19/hardware/tools/arm/bin/../lib/gcc/arm-none-eabi/11.3.1/thumb/v7e-m/nofp\libc.a(libc_a-writer.o): in function `_write_r':

(.text._write_r+0x14): undefined reference to `_write'

collect2.exe: error: ld returned 1 exit status

Using library EEPROM at version 2.0 in folder: C:\arduino-1.8.19\hardware\teensy\avr\libraries\EEPROM 

Error compiling for board Teensy 3.2 / 3.1.
```

**Comment by djpeterso23662** [comment]
Okay, I received errors compiling with teensyduino 1.58, and with 1.57.  But no errors and a successful compile with teensyduino 1.56.  Successfully loaded firmware.  This is with Arduino 1.8.19.
